import { z } from "zod";

export const inventoryActionSchema = z.enum([
  "AWD_TRANSFER",
  "SEA_SHIP",
  "URGENT_AIR_OR_TRANSFER",
  "HOLD_EXCESS",
  "REVIEW_DATA",
  "NO_ACTION",
]);

export const inventoryRiskSchema = z.enum(["critical", "watch", "healthy", "excess", "data"]);

export const inventoryParametersSchema = z.object({
  leadTimeDays: z.number().int().positive(),
  reviewCycleDays: z.number().int().nonnegative(),
  targetCoverDays: z.number().int().nonnegative(),
  safetyStockDays: z.number().int().nonnegative(),
  excessCoverDays: z.number().int().positive(),
  fbaTransferTriggerDays: z.number().int().positive(),
  purchaseOrderOverdueDays: z.number().int().positive(),
});

export const pendingOrderSchema = z.object({
  poNumber: z.string(),
  poDate: z.string(),
  factory: z.string(),
  orderedQuantity: z.number().int().nonnegative(),
  remainingQuantity: z.number().int().nonnegative(),
  sourceRemainingQuantity: z.number().int().nonnegative(),
  expectedDeliveryDate: z.string(),
  ageDays: z.number().int().nonnegative(),
  overdueDays: z.number().int().nonnegative(),
  overdue: z.boolean(),
});

export const inventoryRowSchema = z.object({
  sku: z.string().min(1),
  productName: z.string(),
  factory: z.string(),
  cartonQty: z.number().int().positive().nullable(),
  domesticSupplyTotal: z.number().int().nonnegative().default(0),
  localInventory: z.number().int().nonnegative().default(0),
  pendingOrderQty: z.number().int().nonnegative().default(0),
  pendingOrders: z.array(pendingOrderSchema).default([]),
  readyToShipQty: z.number().int().nonnegative().default(0),
  suggestedProductionQty: z.number().int().nonnegative().default(0),
  fbaSellable: z.number().int().nonnegative(),
  fbaReservedTransfer: z.number().int().nonnegative(),
  fbaReservedProcessing: z.number().int().nonnegative(),
  awdOnHand: z.number().int().nonnegative(),
  awdAvailable: z.number().int().nonnegative(),
  awdPendingShipment: z.number().int().nonnegative(),
  awdOutboundToFba: z.number().int().nonnegative(),
  awdInbound: z.number().int().nonnegative(),
  awdFbaReconciliation: z.number().int().nonnegative(),
  inTransitInventory: z.number().int().nonnegative().default(0),
  dailySales: z.number().nonnegative(),
  salesByMonth: z.array(z.object({ month: z.string(), units: z.number().nonnegative() })),
  salesHistoryByMonth: z.array(z.object({ month: z.string(), units: z.number().nonnegative() })).default([]),
  dataQuality: z.array(z.string()),
  eligibleInventoryPosition: z.number().int().nonnegative(),
  daysCoverFba: z.number().nonnegative().nullable(),
  daysCoverNetwork: z.number().nonnegative().nullable(),
  suggestedShipmentQty: z.number().int().nonnegative(),
  suggestedAwdTransferQty: z.number().int().nonnegative(),
  action: inventoryActionSchema,
  riskLevel: inventoryRiskSchema,
  reason: z.string(),
});

export const inventoryDashboardSchema = z.object({
  schemaVersion: z.literal(2),
  generatedAt: z.string(),
  market: z.string(),
  currency: z.string().length(3),
  domesticPool: z.object({
    id: z.string().min(1),
    sharedAcrossMarkets: z.boolean(),
    markets: z.array(z.string()),
    sourceSheet: z.string(),
  }).default({ id: "CN-SHARED", sharedAcrossMarkets: true, markets: ["US", "CA"], sourceSheet: "库存规划" }),
  snapshots: z.object({
    fbaDate: z.string(),
    awdDate: z.string(),
    alignmentGapDays: z.number().int().nonnegative(),
    aligned: z.boolean(),
    ageDays: z.number().int().nonnegative(),
    staleAfterDays: z.number().int().positive(),
    isStale: z.boolean(),
    awdSourceAvailable: z.boolean(),
  }),
  sales: z.object({
    sourceKind: z.string(),
    sourceSheet: z.string(),
    windowMonths: z.array(z.string()),
    historyMonths: z.array(z.string()).default([]),
    ageDaysAtSnapshot: z.number().int(),
    confidence: z.enum(["low", "medium", "high"]),
    method: z.string(),
    historyMethod: z.string().default(""),
  }),
  businessPerformance: z.object({
    actualYear: z.number().int(),
    forecastYear: z.number().int(),
    series: z.array(z.object({
      month: z.string(),
      actualUnits: z.number().int().nonnegative(),
      forecastUnits: z.number().int().nonnegative(),
      actualRevenue: z.number().nonnegative(),
      promotionRevenue: z.number().nonnegative(),
      advertisingRevenue: z.number().nonnegative(),
    })),
    summary: z.object({
      annualActualUnits: z.number().int().nonnegative(),
      annualActualRevenue: z.number().nonnegative(),
      annualAdvertisingRevenue: z.number().nonnegative(),
      latestMonthUnits: z.number().int().nonnegative(),
      latestMonthRevenue: z.number().nonnegative(),
      latestMonthUnitChangePercent: z.number().nullable(),
    }),
  }),
  advertising: z.object({
    latestMonth: z.string().nullable(),
    ageDaysAtSnapshot: z.number().int().nullable(),
    confidence: z.enum(["low", "medium", "high"]),
    parameters: z.object({
      targetAcosPercent: z.number().positive(),
      minimumEvidenceSpend: z.number().nonnegative(),
      noOrderSpend: z.number().nonnegative(),
      winnerMinOrders: z.number().int().nonnegative(),
      scaleMinOrders: z.number().int().nonnegative(),
      lowVolumeMaxClicks: z.number().int().nonnegative(),
      budgetUtilizationThresholdPercent: z.number().positive(),
      scaleMaxAcosRatio: z.number().positive(),
    }),
    monthlySeries: z.array(z.object({
      month: z.string(),
      spend: z.number().nonnegative(),
      advertisingSales: z.number().nonnegative(),
      orders: z.number().int().nonnegative(),
      clicks: z.number().int().nonnegative(),
      impressions: z.number().int().nonnegative(),
      acos: z.number().nullable(),
      roas: z.number().nullable(),
    })),
    campaigns: z.array(z.object({
      campaign: z.string(),
      sku: z.string().nullable(),
      status: z.string(),
      budget: z.number().nonnegative(),
      spend: z.number().nonnegative(),
      advertisingSales: z.number().nonnegative(),
      orders: z.number().int().nonnegative(),
      clicks: z.number().int().nonnegative(),
      impressions: z.number().int().nonnegative(),
      periodDays: z.number().int().positive(),
      inventoryRisk: inventoryRiskSchema.nullable(),
      inventoryDaysCover: z.number().nullable(),
      acos: z.number().nullable(),
      roas: z.number().nullable(),
      ctr: z.number().nullable(),
      conversionRate: z.number().nullable(),
      averageDailySpend: z.number().nonnegative(),
      budgetUtilizationPercent: z.number().nullable(),
      action: z.enum([
        "PAUSE_STOCK_RISK",
        "NO_ORDER_REVIEW",
        "REDUCE_BID_OR_BUDGET",
        "INCREASE_BID",
        "INCREASE_BUDGET",
        "EXPAND_WINNER",
        "NO_CHANGE_LOW_DATA",
        "MONITOR",
      ]),
      reason: z.string(),
    })),
  }),
  parameters: inventoryParametersSchema,
  sources: z.array(z.object({
    kind: z.string(),
    path: z.string(),
    modifiedAt: z.string(),
    sha256: z.string(),
  })),
  summary: z.object({
    skuCount: z.number().int().nonnegative(),
    fbaSellable: z.number().int().nonnegative(),
    awdAvailable: z.number().int().nonnegative(),
    awdOutboundToFba: z.number().int().nonnegative(),
    awdInboundNotCounted: z.number().int().nonnegative(),
    inTransitInventory: z.number().int().nonnegative().default(0),
    localInventory: z.number().int().nonnegative().default(0),
    pendingOrderQty: z.number().int().nonnegative().default(0),
    overdueOrderCount: z.number().int().nonnegative().default(0),
    overduePurchaseOrderCount: z.number().int().nonnegative().default(0),
    overdueOrderSkuCount: z.number().int().nonnegative().default(0),
    readyToShipQty: z.number().int().nonnegative().default(0),
    suggestedProductionQty: z.number().int().nonnegative().default(0),
    criticalSkuCount: z.number().int().nonnegative(),
    reviewSkuCount: z.number().int().nonnegative(),
    suggestedShipmentQty: z.number().int().nonnegative(),
  }),
  dataQuality: z.object({
    invalidFbaSkuRows: z.number().int().nonnegative(),
    invalidAwdSkuRows: z.number().int().nonnegative(),
    missingSalesSkuCount: z.number().int().nonnegative(),
    missingCartonSkuCount: z.number().int().nonnegative(),
  }),
  rows: z.array(inventoryRowSchema),
});

export const profitabilityRowSchema = z.object({
  market: z.enum(["US", "CA", "MX"]),
  currency: z.enum(["USD", "CAD", "MXN"]),
  reportMonth: z.string(),
  sku: z.string().min(1),
  units: z.number().int().nonnegative(),
  returns: z.number().int().nonnegative(),
  netUnits: z.number().int().nonnegative(),
  productSales: z.number(),
  settlementPayout: z.number(),
  landedCost: z.number().nonnegative(),
  grossProfit: z.number(),
  advertisingCost: z.number().nonnegative(),
  storageCost: z.number().nonnegative(),
  actualProfit: z.number(),
  currentPrice: z.number().nullable(),
  grossMargin: z.number().nullable(),
  actualMargin: z.number().nullable(),
  conservativeMargin: z.number().nullable(),
});

export const profitabilityDataSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string(),
  method: z.string(),
  sources: z.array(z.object({
    market: z.enum(["US", "CA", "MX"]),
    reportMonth: z.string(),
    path: z.string(),
    modifiedAt: z.string(),
    sha256: z.string(),
    sheet: z.string(),
  })),
  rows: z.array(profitabilityRowSchema),
});

export const purchasePlanSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string(),
  cycle: z.object({
    latestOrderDate: z.string(),
    latestStage: z.enum(["mid_month", "month_end"]),
    nextReviewDate: z.string(),
    nextStage: z.enum(["mid_month", "month_end"]),
  }),
  parameters: z.object({
    productionLeadDays: z.number().int().nonnegative(),
    oceanLeadDays: z.number().int().nonnegative(),
    reviewCycleDays: z.number().int().nonnegative(),
    safetyStockDays: z.number().int().nonnegative(),
    demandHorizonDays: z.number().int().positive(),
  }),
  summary: z.object({
    manualPlanSkuCount: z.number().int().nonnegative(),
    manualPlanQuantity: z.number().int().nonnegative(),
    actualOrderSkuCount: z.number().int().nonnegative(),
    actualOrderQuantity: z.number().int().nonnegative(),
    actualPurchaseOrderCount: z.number().int().nonnegative(),
    sourceDocumentCount: z.number().int().nonnegative(),
    matchedSkuCount: z.number().int().nonnegative(),
    discrepancySkuCount: z.number().int().nonnegative(),
    varianceQuantity: z.number().int(),
    nextCycleSkuCount: z.number().int().nonnegative(),
    nextCycleQuantity: z.number().int().nonnegative(),
    criticalSkuCount: z.number().int().nonnegative(),
  }),
  sources: z.array(z.object({
    kind: z.string(),
    path: z.string(),
    sheet: z.string().optional(),
    column: z.string().optional(),
    header: z.string().optional(),
    available: z.boolean().optional(),
    reason: z.string().optional(),
    documentCount: z.number().int().nonnegative().optional(),
  })),
  rows: z.array(z.object({
    sku: z.string(),
    productName: z.string(),
    factory: z.string(),
    cartonQty: z.number().int().positive(),
    usDailySales: z.number().nonnegative(),
    caDailySales: z.number().nonnegative(),
    combinedDailySales: z.number().nonnegative(),
    usNetworkInventory: z.number().int().nonnegative(),
    caNetworkInventory: z.number().int().nonnegative(),
    localInventory: z.number().int().nonnegative(),
    sourcePendingOrderQty: z.number().int().nonnegative().default(0),
    unreflectedLatestOrderQty: z.number().int().nonnegative().default(0),
    pendingOrderQty: z.number().int().nonnegative(),
    inventoryPosition: z.number().int().nonnegative(),
    projectedDemand: z.number().int().nonnegative(),
    coverageDays: z.number().nonnegative().nullable(),
    suggestedPurchaseQty: z.number().int().nonnegative(),
    usPlannedQty: z.number().int().nonnegative(),
    caPlannedQty: z.number().int().nonnegative(),
    manualPlannedQty: z.number().int().nonnegative(),
    actualOrderedQty: z.number().int().nonnegative(),
    varianceQty: z.number().int(),
    reconciliationStatus: z.enum(["MATCHED", "ORDERED_MORE", "ORDERED_LESS", "PLAN_ONLY", "ORDER_ONLY", "NO_ORDER"]),
    riskLevel: z.enum(["critical", "watch", "healthy", "data"]),
    orders: z.array(z.object({
      poNumber: z.string(),
      factory: z.string(),
      quantity: z.number().int().nonnegative(),
      unitPrice: z.number().nonnegative(),
      sourcePath: z.string(),
    })),
  })),
});

export const variantCatalogSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string(),
  groups: z.array(z.object({
    market: z.string(),
    parentSku: z.string(),
    familyId: z.string(),
    categoryL1: z.string(),
    categoryL2: z.string(),
    familyName: z.string(),
    variationTheme: z.string(),
    childCount: z.number().int().nonnegative(),
    note: z.string(),
  })),
  items: z.array(z.object({
    market: z.string(),
    parentSku: z.string(),
    familyId: z.string(),
    role: z.string(),
    sku: z.string(),
    productName: z.string(),
    categoryL1: z.string(),
    categoryL2: z.string(),
    familyName: z.string(),
    variationTheme: z.string(),
    variantValue: z.string(),
    amazonItemType: z.string(),
    sourceFile: z.string(),
    confidence: z.string(),
    dataQuality: z.string(),
    reviewStatus: z.string(),
  })),
});

const nullableNumber = z.number().nonnegative().nullable();

export const productCatalogSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string(),
  sources: z.array(z.object({
    kind: z.string(),
    path: z.string(),
    modifiedAt: z.string(),
    sha256: z.string(),
  })),
  items: z.array(z.object({
    sku: z.string(),
    fnsku: z.string(),
    productDescription: z.string(),
    category: z.string(),
    packaging: z.string(),
    hsCode: z.string(),
    englishName: z.string(),
    chineseName: z.string(),
    declarationElements: z.string(),
    declarationElementsEnglish: z.string(),
    cartonQty: z.number().int().positive().nullable(),
    cartonNetWeightKg: nullableNumber,
    cartonGrossWeightKg: nullableNumber,
    cartonDimensionsCm: z.object({ length: nullableNumber, width: nullableNumber, height: nullableNumber }),
    cartonVolumeM3: nullableNumber,
    productWeightG: nullableNumber,
    shippingSizeCm: z.string(),
    purchaseCostRmbTaxIncluded: nullableNumber,
    purchaseCostRmbTaxExcluded: nullableNumber,
    purchaseCostUsd: nullableNumber,
    imageFile: z.string(),
    imageMimeType: z.string(),
    imageSha256: z.string(),
    listing: z.object({
      brand: z.string(),
      title: z.string(),
      description: z.string(),
      bullets: z.array(z.string()),
      attributes: z.record(z.string(), z.string()),
      engineeringNotes: z.array(z.string()),
      sourceSheet: z.string(),
    }).nullable(),
  })),
});

export const newProductResearchSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string(),
  source: z.object({ path: z.string(), modifiedAt: z.string(), sha256: z.string(), sheet: z.string() }),
  summary: z.object({
    candidateCount: z.number().int().nonnegative(),
    viableCandidateCount: z.number().int().nonnegative(),
    averageGrossMargin: z.number(),
    latestOrderMonth: z.string().nullable(),
    orderedSkuCount: z.number().int().nonnegative(),
    plannedUnits: z.number().int().nonnegative(),
    monthCount: z.number().int().nonnegative(),
  }),
  candidates: z.array(z.object({
    sku: z.string(), name: z.string(), amazonPrice: z.number().nullable(), firstMile: z.number().nullable(), storageFee: z.number().nullable(), commission: z.number().nullable(), orderFee: z.number().nullable(), importDutyRate: z.number().nullable(), purchaseCostRmb: z.number().nullable(), untaxedPriceUsd: z.number().nullable().default(null), totalCostUsd: z.number().nullable().default(null), grossProfit: z.number().nullable(), grossMargin: z.number().nullable(), competitorUrl: z.string(),
  })),
  monthlyOrders: z.array(z.object({ month: z.string(), sku: z.string(), name: z.string(), orderQuantity: z.number().nullable(), costRmb: z.number().nullable(), status: z.string(), usStatus: z.string(), caStatus: z.string() })),
});

const contentSectionSchema = z.object({
  section: z.string(),
  channel: z.enum(["main_image", "a_plus"]),
  size: z.string(),
  copy: z.string(),
  requirement: z.string(),
  sourceRow: z.number().int().positive().nullable(),
});

export const contentWorkflowSchema = z.object({
  schemaVersion: z.literal(1),
  generatedAt: z.string(),
  summary: z.object({
    taskCount: z.number().int().nonnegative(),
    listingMasterCount: z.number().int().nonnegative(),
    generatedCopyCount: z.number().int().nonnegative(),
    mainImageArchiveCount: z.number().int().nonnegative(),
    aPlusArchiveCount: z.number().int().nonnegative(),
    archiveBriefCount: z.number().int().nonnegative(),
    mappedArchiveBriefCount: z.number().int().nonnegative(),
    exceptionCount: z.number().int().nonnegative(),
  }),
  tasks: z.array(z.object({
    sku: z.string(),
    productName: z.string(),
    category: z.string(),
    imageFile: z.string(),
    status: z.literal("draft_review_required"),
    copy: z.object({
      source: z.enum(["listing_master", "structured_product_draft"]),
      title: z.string(),
      bullets: z.array(z.string()),
      description: z.string(),
      qualityFlags: z.array(z.string()),
    }),
    mainImageBrief: z.object({ source: z.enum(["creative_archive", "generated_template"]), sections: z.array(contentSectionSchema) }),
    aPlusBrief: z.object({ source: z.enum(["creative_archive", "generated_template"]), sections: z.array(contentSectionSchema) }),
    sourceBriefIds: z.array(z.string()),
  })),
});

export type InventoryAction = z.infer<typeof inventoryActionSchema>;
export type InventoryRisk = z.infer<typeof inventoryRiskSchema>;
export type InventoryParameters = z.infer<typeof inventoryParametersSchema>;
export type PendingOrder = z.infer<typeof pendingOrderSchema>;
export type InventoryRow = z.infer<typeof inventoryRowSchema>;
export type InventoryDashboardData = z.infer<typeof inventoryDashboardSchema>;
export type ProfitabilityData = z.infer<typeof profitabilityDataSchema>;
export type PurchasePlanData = z.infer<typeof purchasePlanSchema>;
export type PurchasePlanRow = PurchasePlanData["rows"][number];
export type AdvertisingCampaign = InventoryDashboardData["advertising"]["campaigns"][number];
export type AdvertisingParameters = InventoryDashboardData["advertising"]["parameters"];
export type AdvertisingAction = AdvertisingCampaign["action"];
export type VariantCatalogData = z.infer<typeof variantCatalogSchema>;
export type ProductCatalogData = z.infer<typeof productCatalogSchema>;
export type ProductCatalogItem = ProductCatalogData["items"][number];
export type NewProductResearchData = z.infer<typeof newProductResearchSchema>;
export type ContentWorkflowData = z.infer<typeof contentWorkflowSchema>;
export type ContentWorkflowTask = ContentWorkflowData["tasks"][number];
