import { ArrowDownRight, ChartSpline, CircleAlert } from "lucide-react";

import { OpsBadge, OpsCard, OpsCardHeader, OpsKpi } from "@/components/inventory/ops-ui";
import type { PurchaseBacktestResult } from "@/lib/inventory/purchase-backtest";

export function PurchaseBacktestView({ result }: { result: PurchaseBacktestResult }) {
  const baseline = result.methods.find((method) => method.method === "recent3"); const best = result.methods[0]; const improvement = Math.max(0, (baseline?.weightedErrorPercent ?? 0) - (best?.weightedErrorPercent ?? 0));
  return <div className="space-y-5">
    <div className="flex items-start gap-3 border border-blue-200 bg-blue-50 px-4 py-3 text-xs leading-5 text-blue-900"><CircleAlert className="mt-0.5 h-4 w-4 shrink-0" /><p>这是只读回测，不会修改采购建议。系统使用历史月份逐月模拟预测，对比后仍需人工确认是否按 SKU 类型启用新算法。</p></div>
    <div className="ops-kpi-grid grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><OpsKpi label="回测 SKU" value={`${result.skuCount} 个`} detail={`${result.months.at(0)} 至 ${result.months.at(-1)}`} /><OpsKpi label="断续需求 SKU" value={`${result.intermittentSkuCount} 个`} detail="零销量月份占比 ≥ 25%" tone="warning" /><OpsKpi label="整体最优" value={result.recommendedLabel} detail={`${best?.weightedErrorPercent ?? 0}% 加权误差`} tone="positive" /><OpsKpi label="相对基线改善" value={`${improvement.toFixed(1)} 个百分点`} detail="仅回测结果，不改默认口径" tone={improvement > 0 ? "positive" : "default"} /><OpsKpi label="可优化 SKU" value={`${result.topImprovements.length} 个`} detail="非基线模型改善超过 1%" /></div>
    <OpsCard><OpsCardHeader title="模型总体表现" description={`${result.recommendedLabel} 当前加权误差最低（${best?.weightedErrorPercent.toFixed(1) ?? "—"}%），较近 3 月均值改善 ${improvement.toFixed(1)} 个百分点。`} action={<ChartSpline className="h-4 w-4 text-emerald-700" />} /><div className="grid border-t border-slate-100 md:grid-cols-3">{result.methods.map((method, index) => <div key={method.method} className="border-b border-slate-100 p-5 md:border-r"><div className="flex items-center justify-between gap-3"><p className="text-sm font-semibold">{method.label}</p>{index === 0 ? <OpsBadge tone="emerald">本次最优</OpsBadge> : null}</div><p className="mt-4 text-3xl font-semibold tracking-tight">{method.weightedErrorPercent.toFixed(1)}%</p><div className="mt-3 flex justify-between text-[11px] text-slate-500"><span>偏差 {method.biasPercent > 0 ? "+" : ""}{method.biasPercent.toFixed(1)}%</span><span>{method.winningSkuCount} 个 SKU 最优</span><span>{method.evaluatedPoints} 个测试点</span></div></div>)}</div></OpsCard>
    <OpsCard><OpsCardHeader title="SKU 级优化候选" description={result.topImprovements[0] ? `${result.topImprovements.length} 个 SKU 可优化，其中 ${result.topImprovements[0].sku} 预计可降低误差 ${(result.topImprovements[0].baselineError - result.topImprovements[0].bestError).toFixed(1)} 个百分点。` : "本次回测没有发现显著优于当前基线的 SKU。"} /><div className="overflow-x-auto"><table className="w-full min-w-[780px] text-left text-xs"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-4 py-3">SKU / 产品</th><th className="px-3 py-3">建议模型</th><th className="px-3 py-3 text-right">基线误差</th><th className="px-3 py-3 text-right">替代误差</th><th className="px-3 py-3 text-right">改善</th><th className="px-4 py-3 text-right">零销量占比</th></tr></thead><tbody className="divide-y divide-slate-100">{result.topImprovements.map((item) => <tr key={item.sku}><td className="px-4 py-3"><p className="font-mono font-semibold text-emerald-700">{item.sku}</p><p className="mt-1 max-w-80 truncate text-slate-500">{item.productName}</p></td><td className="px-3 py-3"><OpsBadge tone={item.bestMethod === "croston" ? "blue" : "amber"}>{item.bestLabel}</OpsBadge></td><td className="px-3 py-3 text-right">{item.baselineError.toFixed(1)}%</td><td className="px-3 py-3 text-right font-semibold text-emerald-700">{item.bestError.toFixed(1)}%</td><td className="px-3 py-3 text-right"><span className="inline-flex items-center text-emerald-700"><ArrowDownRight className="h-3.5 w-3.5" />{(item.baselineError - item.bestError).toFixed(1)}%</span></td><td className="px-4 py-3 text-right">{item.zeroSharePercent.toFixed(0)}%</td></tr>)}</tbody></table></div></OpsCard>
  </div>;
}
